pipeline {
    agent any

    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'b1a0fad1-4560-4122-abef-130cfc9bdfd4', url: 'https://github.com/ParimalaSreeR/Jenkins_Setup.git']])
            }
        }
        stage('Build') {
            steps {
                bat 'javac Hello.java'
                bat 'java Hello'
            }
        }
        stage('Testing') {
            steps {
                echo "This job has tested"
            }
        }
        
        stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', url: 'https://github.com/ParimalaSreeR/emptyrepo.git'
            }
        }
        stage('Check file') {
            steps {
                sh 'ls -l'
                sh 'if [ -f tiaa.json ]; then echo "File exists"; else echo "File does not exist"; exit 1; fi'
                sh 'if [ ! -s tiaa.json ]; then echo "File is empty"; exit 1; fi'
                sh 'if [ "$(cat tiaa.json | python -m json.tool 2>&1 >/dev/null)" != "" ]; then echo "File is not valid JSON"; exit 1; fi'
            }
        }
    }
    }
    
}
